services:
  caddy:
    image: caddy:2-alpine
    networks:
    - frappe_network
    ports:
    - 80:80
    - 443:443
    volumes:
    - ./Caddyfile:/etc/caddy/Caddyfile
    - caddy_data:/data
    - caddy_config:/config
    deploy:
      restart_policy:
        condition: on-failure
  backend:
    image: 835156585962.dkr.ecr.us-east-1.amazonaws.com/greenfoot:latest
    networks:
    - frappe_network
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
    - sites:/home/frappe/frappe-bench/sites
    - logs:/home/frappe/frappe-bench/logs
    - ./apps/kraken_theme:/home/frappe/frappe-bench/apps/kraken_theme
    - ./apps/warranties:/home/frappe/frappe-bench/apps/warranties
    environment:
      DB_HOST: db
      DB_PORT: '3306'
      MYSQL_ROOT_PASSWORD: admin
      MARIADB_ROOT_PASSWORD: admin
  configurator:
    image: 835156585962.dkr.ecr.us-east-1.amazonaws.com/greenfoot:latest
    networks:
    - frappe_network
    deploy:
      restart_policy:
        condition: none
    entrypoint:
    - bash
    - -c
    command:
    - 'ls -1 apps > sites/apps.txt; bench set-config -g db_host $$DB_HOST; bench set-config
      -gp db_port $$DB_PORT; bench set-config -g redis_cache "redis://$$REDIS_CACHE";
      bench set-config -g redis_queue "redis://$$REDIS_QUEUE"; bench set-config -g
      redis_socketio "redis://$$REDIS_QUEUE"; bench set-config -gp socketio_port $$SOCKETIO_PORT;

      '
    environment:
      DB_HOST: db
      DB_PORT: '3306'
      REDIS_CACHE: redis-cache:6379
      REDIS_QUEUE: redis-queue:6379
      SOCKETIO_PORT: '9000'
    volumes:
    - sites:/home/frappe/frappe-bench/sites
    - logs:/home/frappe/frappe-bench/logs
    - ./apps/kraken_theme:/home/frappe/frappe-bench/apps/kraken_theme
    - ./apps/warranties:/home/frappe/frappe-bench/apps/warranties
  create-site:
    image: 835156585962.dkr.ecr.us-east-1.amazonaws.com/greenfoot:latest
    networks:
    - frappe_network
    deploy:
      restart_policy:
        condition: none
    volumes:
    - sites:/home/frappe/frappe-bench/sites
    - logs:/home/frappe/frappe-bench/logs
    - ./apps/kraken_theme:/home/frappe/frappe-bench/apps/kraken_theme
    - ./apps/warranties:/home/frappe/frappe-bench/apps/warranties
    entrypoint:
    - bash
    - -c
    command:
    - "wait-for-it -t 120 db:3306; wait-for-it -t 120 redis-cache:6379; wait-for-it\
      \ -t 120 redis-queue:6379; export start=`date +%s`; until [[ -n `grep -hs ^\
      \ sites/common_site_config.json | jq -r \".db_host // empty\"` ]] && \\\n  [[\
      \ -n `grep -hs ^ sites/common_site_config.json | jq -r \".redis_cache // empty\"\
      ` ]] && \\\n  [[ -n `grep -hs ^ sites/common_site_config.json | jq -r \".redis_queue\
      \ // empty\"` ]];\ndo\n  echo \"Waiting for sites/common_site_config.json to\
      \ be created\";\n  sleep 5;\n  if (( `date +%s`-start > 120 )); then\n    echo\
      \ \"could not find sites/common_site_config.json with required keys\";\n   \
      \ exit 1\n  fi\ndone; echo \"sites/common_site_config.json found\"; bench new-site\
      \ --mariadb-user-host-login-scope='%' --admin-password=admin --db-root-username=root\
      \ --db-root-password=admin --install-app erpnext --install-app kraken_theme\
      \ --install-app warranties --set-default greenfoot-energy.mythril.cloud;\n"
  db:
    image: mariadb:10.6
    networks:
    - frappe_network
    healthcheck:
      test: mysqladmin ping -h localhost --password=admin
      interval: 1s
      retries: 20
    deploy:
      restart_policy:
        condition: on-failure
    command:
    - --character-set-server=utf8mb4
    - --collation-server=utf8mb4_unicode_ci
    - --skip-character-set-client-handshake
    - --skip-innodb-read-only-compressed
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MARIADB_ROOT_PASSWORD: admin
    volumes:
    - db-data:/var/lib/mysql
  frontend:
    image: 835156585962.dkr.ecr.us-east-1.amazonaws.com/greenfoot:latest
    networks:
    - frappe_network
    depends_on:
    - websocket
    deploy:
      restart_policy:
        condition: on-failure
    command:
    - nginx-entrypoint.sh
    environment:
      BACKEND: backend:8000
      FRAPPE_SITE_NAME_HEADER: greenfoot-energy.mythril.cloud
      SOCKETIO: websocket:9000
      UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
      UPSTREAM_REAL_IP_RECURSIVE: 'off'
      PROXY_READ_TIMEOUT: 120
      CLIENT_MAX_BODY_SIZE: 50m
    volumes:
    - sites:/home/frappe/frappe-bench/sites
    - logs:/home/frappe/frappe-bench/logs
    - ./apps/kraken_theme:/home/frappe/frappe-bench/apps/kraken_theme
    - ./apps/warranties:/home/frappe/frappe-bench/apps/warranties
  queue-long:
    image: 835156585962.dkr.ecr.us-east-1.amazonaws.com/greenfoot:latest
    networks:
    - frappe_network
    deploy:
      restart_policy:
        condition: on-failure
    command:
    - bench
    - worker
    - --queue
    - long,default,short
    volumes:
    - sites:/home/frappe/frappe-bench/sites
    - logs:/home/frappe/frappe-bench/logs
    - ./apps/kraken_theme:/home/frappe/frappe-bench/apps/kraken_theme
    - ./apps/warranties:/home/frappe/frappe-bench/apps/warranties
    environment:
      FRAPPE_REDIS_CACHE: redis://redis-cache:6379
      FRAPPE_REDIS_QUEUE: redis://redis-queue:6379
  queue-short:
    image: 835156585962.dkr.ecr.us-east-1.amazonaws.com/greenfoot:latest
    networks:
    - frappe_network
    deploy:
      restart_policy:
        condition: on-failure
    command:
    - bench
    - worker
    - --queue
    - short,default
    volumes:
    - sites:/home/frappe/frappe-bench/sites
    - logs:/home/frappe/frappe-bench/logs
    - ./apps/kraken_theme:/home/frappe/frappe-bench/apps/kraken_theme
    - ./apps/warranties:/home/frappe/frappe-bench/apps/warranties
    environment:
      FRAPPE_REDIS_CACHE: redis://redis-cache:6379
      FRAPPE_REDIS_QUEUE: redis://redis-queue:6379
  redis-queue:
    image: redis:6.2-alpine
    networks:
    - frappe_network
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
    - redis-queue-data:/data
  redis-cache:
    image: redis:6.2-alpine
    networks:
    - frappe_network
    deploy:
      restart_policy:
        condition: on-failure
  scheduler:
    image: 835156585962.dkr.ecr.us-east-1.amazonaws.com/greenfoot:latest
    networks:
    - frappe_network
    deploy:
      restart_policy:
        condition: on-failure
    command:
    - bench
    - schedule
    volumes:
    - sites:/home/frappe/frappe-bench/sites
    - logs:/home/frappe/frappe-bench/logs
    - ./apps/kraken_theme:/home/frappe/frappe-bench/apps/kraken_theme
    - ./apps/warranties:/home/frappe/frappe-bench/apps/warranties
  websocket:
    image: 835156585962.dkr.ecr.us-east-1.amazonaws.com/greenfoot:latest
    networks:
    - frappe_network
    deploy:
      restart_policy:
        condition: on-failure
    command:
    - node
    - /home/frappe/frappe-bench/apps/frappe/socketio.js
    environment:
      FRAPPE_REDIS_CACHE: redis://redis-cache:6379
      FRAPPE_REDIS_QUEUE: redis://redis-queue:6379
    volumes:
    - sites:/home/frappe/frappe-bench/sites
    - logs:/home/frappe/frappe-bench/logs
    - ./apps/kraken_theme:/home/frappe/frappe-bench/apps/kraken_theme
    - ./apps/warranties:/home/frappe/frappe-bench/apps/warranties
volumes:
  db-data: null
  redis-queue-data: null
  sites: null
  logs: null
  caddy_data: null
  caddy_config: null
networks:
  frappe_network:
    driver: bridge
